weather/urls.py
from django.urls import path,include
from . import views
app_name = 'Weather'
urlpatterns = [
    path('',views.index,name='index')
]

weather_io/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('weather.urls')),
]

weather/models.py
from pyexpat import model
from django.db import models

# Create your models here.


class City(models.Model):
    cityName = models.CharField(max_length=200)
    
    def __str__(self):
        return self.cityName
    class Meta:
        ordering =['cityName']

weather/forms.py
from django import forms


class CityForm(forms.Form):
    CityName = forms.CharField(max_length=200,label='Search City or Zip Code')
    
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for fields_name in self.fields:
            field = self.fields.get(fields_name)
            self.fields[fields_name].widget.attrs.update({'placeholder':field.label})

weather/views.py
from contextvars import Context
import io
import json
from django.shortcuts import render
from django.template import context
import requests
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import City
from . forms import CityForm
# Create your views here.
from weather_io.settings import Ap_ID

def urlCall(request,CityName,ApID):
    weather_datas = []
    ApID = Ap_ID
    url = 'https://api.openweathermap.org/data/2.5/weather?q={}&appid={}'.format(CityName,ApID)
    weather = requests.get(url)
    data = json.loads(weather.text)
    try:
        url2 = 'https://api.openweathermap.org/data/2.5/onecall?lat={}&lon={}&appid={}'.format(data['coord']['lat'],data['coord']['lon'],ApID)
        weather2 = requests.get(url2)
    except:
        form = CityForm()
        return render(request,'weather/index.html',{'form':form})
    data2 = json.loads(weather2.text)
     
    weather_data = {
                'currentCounrty':data['sys']['country'],
                'currentName':data['name'],
                'currentTime':data2['current']['dt'],
                'currentTemp':data2['current']['temp'],
                'currentHumidity':data2['current']['humidity'],
                'currentWeatherM':data2['current']['weather'][0]['main'],
                'currentWeatherIcon':data2['current']['weather'][0]['icon'],
                'currentWeatherdesc':data2['current']['weather'][0]['description'],
                'currentWeatherdesc':data2['current']['weather'][0]['description'],
                'currentVisibility':data2['current']['visibility']/100,
                
                'hourlydt':data2['hourly'][0]['dt'],
                'hourlyTemp':data2['hourly'][0]['temp'],
                'hourlyFl':data2['hourly'][0]['feels_like'],
                'hourlyHd':data2['hourly'][0]['humidity'],
                'hourlyCld':data2['hourly'][0]['clouds'],
                'hourlyUvi':data2['hourly'][0]['uvi'],
                'hourlyVsis':data2['hourly'][0]['visibility'],
                
                'hourlyWeatherIcon':data2['hourly'][0]['weather'][0]['icon'],
                'hourlyWeatherM':data2['hourly'][0]['weather'][0]['main'],
                'hourlyWeatherDesc':data2['hourly'][0]['weather'][0]['description'],
                
                'dailyDt':data2['daily'][0]['dt'],
                'dailySunrise':data2['daily'][0]['sunrise'], 
                'dailySunset':data2['daily'][0]['sunset'], 
                'dailyMoonset':data2['daily'][0]['moonset'],
                'dailyMoonrise':data2['daily'][0]['moonrise'],
                
                'dailytempDay':data2['daily'][0]['temp']['day'],
                'dailytempNight':data2['daily'][0]['temp']['night'],
                'dailytempEve':data2['daily'][0]['temp']['eve'],
                'dailytempMorn':data2['daily'][0]['temp']['morn'],
                'dailytempMin':data2['daily'][0]['temp']['min'],
                'dailytempMax':data2['daily'][0]['temp']['max'],
                'dailyHumidity':data2['daily'][0]['humidity'],
                'dailyPresure':data2['daily'][0]['pressure'],
                'dailyDew':data2['daily'][0]['dew_point'],
                'dailyMoon':data2['daily'][0]['moon_phase'],
                'dailyWind':data2['daily'][0]['wind_speed']%data2['daily'][0]['wind_deg'],
                
    
                'dailyFeelsDay':data2['daily'][0]['feels_like']['day'],
                'dailyFeelsNight':data2['daily'][0]['feels_like']['night'],
                'dailyFeelsEve':data2['daily'][0]['feels_like']['eve'],
                'dailyFeelsMorn':data2['daily'][0]['feels_like']['morn'],
                
                'dailyWeatherIcon':data2['daily'][0]['weather'][0]['icon'],
                'dailyWeatherMain':data2['daily'][0]['weather'][0]['main'],
                'dailyWeatherDesc':data2['daily'][0]['weather'][0]['description'],
                
                'Currentuvi':data2['daily'][0]['uvi']
                                              
                
            }
    weather_datas.append(weather_data)
            
    return weather_datas
    
def index(request):
   
    ApID = Ap_ID
    print(ApID)
    if request.method == "GET":
        form = CityForm(request.GET)
        if form.is_valid():
            CityName = form.cleaned_data['CityName']
            form = CityForm()
            return render(request,'weather/index.html',{'weather': urlCall(request,CityName,ApID),'form':form})      
    else: 
        form = CityForm()
        
    return render(request,'weather/index.html',{'weather': urlCall(request,City.objects.all()[0],ApID),'form':form})

weather/templates/weather/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Current Weather</title>
    <link rel="stylesheet" href="{% static 'weather\main.css' %}">
    <script src="https://kit.fontawesome.com/18de66c05e.js" crossorigin="anonymous"></script>
</head>
<body>

    <div class="mainRow">
    <div class="col logo"><p>Weather & Road Risk</p></div>
    <div class="col forms_div">
        <form method="GET">
            {% csrf_token %}
            {% for forms in form  %}
            {{forms}}{% endfor %}<input type="submit" value="Search City">
        </form>
    </div>
</div>
<div class="mainRow">
<div class="col weatherMenu">
    <ul>
        <li><a href="{% url 'Weather:index' %}">Today</a></li>
        <li><a href="">Hourly</a></li>
        <li><a href="">WeekEnd</a></li>
        <li><a href="">Monthly</a></li>
        <li><a href="">Radar Map</a></li>
    </ul>
</div>
</div>

<div class="weatherWrapper">
<div class="mainRow">
<div class="col WeatherContainer">
    {% for weathers  in weather %}
        <p>{{weathers.currentName}},&nbsp;{{weathers.currentCounrty}}&nbsp; As Of&nbsp;{{weathers.currentTime}}</p>
    <p><span class="humidity">{{weathers.currentTemp}}<sup>o</sup></span><img src="http://openweathermap.org/img/w/{{weathers.currentWeatherIcon}}.png"></p>
    <p>{{weathers.currentWeatherdesc}}</p>
    <p>Day&nbsp;{{weathers.dailytempDay}}<sup>o</sup>&nbsp;&nbsp;. Night&nbsp;{{weathers.dailytempNight}}<sup>o</sup></p>


{% endfor %}
</div>

<div class="col RoadRisk"></div>
</div>

<div class="mainRow">
    <div class="col  WeatherContainer">
{% for weathers in weather  %}
<h4>Today's Forecast For {{weathers.currentName}} </h4>

  <div class="col weather-item">
      <h5>Morning</h5>
      <p><span>{{weathers.dailytempMorn}}<sup>o</sup></span></p>
      <p><img src="http://openweathermap.org/img/w/{{weathers.hourlyWeatherIcon}}.png"></p>
      <p>{{weathers.dailyHumidity}}%</p>
    </div>
  <div class="col weather-item">
      <h5>Afternoon</h5>
      <p><span>{{weathers.dailytempEve}}<sup>o</sup></span></p>
      <p><img src="http://openweathermap.org/img/w/{{weathers.dailyWeatherIcon}}.png"></p>
      <p>{{weathers.dailyHumidity}}%</p>
      
    
    </div>
  <div class="col weather-item">
      <h5>Evening</h5>
      <p><span>{{weathers.dailytempEve}}<sup>o</sup></span></p>
      <p><img src="http://openweathermap.org/img/w/{{weathers.dailyWeatherIcon}}.png"></p>
      <p>{{weathers.dailyHumidity}}%</p>
    
    
    </div>
  <div class="col weather-item">
      <h5>Night</h5>
      <p><span>{{weathers.dailytempNight}}<sup>o</sup></span></p>
      <p><img src="http://openweathermap.org/img/w/{{weathers.dailyWeatherIcon}}.png"></p>
      <p>{{weathers.dailyHumidity}}%</p>

    {% endfor %}
</div>
        
</div>
    
    </div>
<!--end of today's forecast-->   
<div class="Todays_weather">
    {% for weathers in weather %}
<h2>Weather Today in {{weathers.currentName}},&nbsp;{{weathers.currentCounrty}}</h2>

    <div class="mainRow">
        <div class="col feel">
            <p><span style="font-size:60px;">{{weathers.dailyFeelsDay}}<sup>o</sup></span>
            <br>Feels Like
        </p>
    </div>
            <div class="feel_image">
                <p><img src="http://openweathermap.org/img/w/{{weathers.dailyWeatherIcon}}.png"></p>
                
                
            </div>
        </div>
<div class="mainRow">
    <div class="col levels1">
        <table>
            <tr>
                <td><i class="fa-solid fa-temperature-low"></i>&nbsp;High/Low</td>
                <td>{{weathers.dailytempMax}}<sup>o</sup>/{{weathers.dailytempMin}}<sup>o</sup></td>
            </tr>
            <tr>
                <td><i class="fa-regular fa-droplet-degree"></i>&nbsp;Humidity</td>
                <td>{{weathers.dailyHumidity}}%</td>
            </tr>
            <tr>
                <td>Pressure</td>
                <td>{{weathers.dailyPresure }} mb</td>
            </tr>
            <tr>
                <td><i class="fa-solid fa-eye"></i>&nbsp;Visibility</td>
                <td>{{weathers.currentVisibility}} km</td>
            </tr>
            

        </table>
    </div>

    <div class="col levels2">
        <table>
            <tr>
                <td><i class="fa-solid fa-wind"></i>&nbsp;Wind</td>
                <td>{{weathers.dailyWind}} km/h</td>
            </tr>
            <tr>
                <td><i class="fa-solid fa-temperature-snow"></i>Dew Points</td>
                <td>{{weathers.dailyDew}}%</td>
            </tr>
            <tr>
                <td>Uv index</td>
                <td>{{weathers.Currentuvi}}</td>
            </tr>
            <tr>
                <td><i class="fa-regular fa-moon"></i>&nbsp;Moon Phase</td>
                <td>{{weathers.dailyMoon}}km</td>
            </tr>
            

        </table>
    </div>
</div>
{% endfor %}
</div><!--end of todays weather--> 









</div><!--end of weatherwrapper -->






</body>
</html>